# Config for deploybot.app
# Docs https://docs.deploybot.app/config/
# Ordered list of Github Deployment environments
deployments:
- name: development
# Automatically trigger deploy on default branch passing
# on_push: true
- name: staging
- name: production1
- name: production2
- name: production3
- name: production4
- name: production5
- name: production6
- name: production7
- name: production8
- name: production9
- name: production10
- name: production11
- name: production12
- name: production13
- name: production14
- name: production15
