apiVersion: v1
kind: Service
metadata:
  name: {{ include "angi-helloworld.fullname" . }}
  labels:
    {{- include "angi-helloworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http-web
  selector:
    {{- include "angi-helloworld.selectorLabels" . | nindent 4 }}
